#!/bin/sh

# init script for X11

# load key configuration
xmodmap ~/.config/Xmodmap

# source xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ]
then
	for script in /etc/X11/xinit/xinitrc.d/?*.sh
	do
		[ -x "$script" ] && source "$script"
	done
	unset script
fi

# hide the cursor when a key is pressed
xbanish &

# hotkeys
sxhkd &

# clipboard manager
clipmenud &

# disable DPMS
xset dpms 0 0 0

# set background image
feh --no-fehbg --randomize --bg-fill ~/documents/wallpapers/*

# use dbus and i3wm
exec dbus-launch --exit-with-session i3
